# our routes
wiki_stage_web:
    resource: "@WikiStageWebBundle/Resources/config/routing.yml"
    prefix:   /

# Sonata routes
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
