WikiStage\Bundle\CoreBundle\Entity\Event:
    type:   entity
    table:  event
    fields:
        id:
            type:       integer
            id:         true
            generator:
                strategy: AUTO
        name:
            type:       string
        date:
            type:       datetime
        place:
            type:       string
        address: # Will be an object of class Genemu\Bundle\FormBundle\Geolocation\AddressGeolocation
            type:       object
            nullable:   true
        description:
            type:       text
            nullable:   true
        links:
            type:       json_array
            nullable:   true
        # picture
        gallery_url:
            type:       string
            nullable:   true
    oneToMany:
        videos:
            targetEntity: Video
            mappedBy:   event
    manyToMany:
        speakers: # owning side
            targetEntity: Speaker
            inversedBy: events

