WikiStage\Bundle\CoreBundle\Entity\User:
    type: entity
    table: user
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            unique: true
        email:
            type: string
            unique: true
        salt:
            type: string
        password:
            type: string
        isActive:
            type: boolean
