parameters:
#    wiki_stage_core.example.class: WikiStage\Bundle\CoreBundle\Example

services:
#    wiki_stage_core.example:
#        class: %wiki_stage_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
